import { VisualDiagram, DiagramCategory } from "../src/types";

export class ServerDiagramEngine {
  private static diagrams: VisualDiagram[] = [
    {
      id: "diag-01",
      title: "IS 456:2000 Singly Reinforced Rectangular Beam Stress Block",
      category: "rcc_structures",
      categoryName: "RCC & Structural Mechanics",
      subjectName: "RCC & Prestressed Concrete",
      caption: "Parabolic-Rectangular stress distribution in concrete and limit state tension parameters as per IS 456:2000 Clause 38.1.",
      accessibilityText: "Diagram shows a rectangular beam cross-section with width b and effective depth d. Beside it is the parabolic-rectangular stress block showing compressive stress 0.446 fck, parabolic depth (3/7)xu, rectangular depth (4/7)xu, total compressive force C = 0.36 fck b xu acting at 0.42 xu from the top, and tensile force T = 0.87 fy Ast at steel centroid.",
      isCodeReference: "IS 456:2000 Cl 38.1 & Fig 21",
      svgType: "rcc_stress_block",
      linkedFormulaId: "f-rcc-01",
      linkedMcqTopic: "Limit State of Collapse - Flexure",
      keyTakeaways: [
        "Maximum compressive strain in concrete in bending is 0.0035.",
        "Concrete compressive stress distribution is parabolic up to strain 0.002 and constant (rectangular) from 0.002 to 0.0035.",
        "Total Compressive Force C = 0.36 * fck * b * xu.",
        "Center of Compressive force acts at distance 0.416 xu ≈ 0.42 xu from outermost compression fiber.",
        "Lever Arm z = d - 0.42 xu.",
        "Total Tensile Force T = 0.87 * fy * Ast.",
      ],
      hotspots: [
        {
          id: "hs-01",
          xPercent: 30,
          yPercent: 12,
          label: "Max Concrete Compressive Strain = 0.0035",
          codeReference: "IS 456 Cl 38.1(b)",
          description: "Outermost compression fiber strain reaches 0.0035 at ultimate limit state of collapse.",
          formulaRelation: "\\varepsilon_{cu} = 0.0035",
        },
        {
          id: "hs-02",
          xPercent: 68,
          yPercent: 12,
          label: "Design Compressive Stress = 0.446 fck",
          codeReference: "IS 456 Cl 38.1(c)",
          description: "Characteristic compressive strength fck multiplied by size factor 0.67 and divided by partial safety factor gamma_m = 1.5. (0.67 / 1.5 = 0.446 fck).",
          formulaRelation: "f_{cd} = \\frac{0.67 f_{ck}}{1.5} = 0.446 f_{ck}",
        },
        {
          id: "hs-03",
          xPercent: 68,
          yPercent: 28,
          label: "Rectangular Stress Portion: (3/7) xu",
          codeReference: "IS 456 Cl 38.1 Fig 21",
          description: "Depth from top where strain varies between 0.002 and 0.0035.",
          formulaRelation: "x_1 = \\frac{3}{7} x_u \\approx 0.43 x_u",
        },
        {
          id: "hs-04",
          xPercent: 68,
          yPercent: 48,
          label: "Parabolic Stress Portion: (4/7) xu",
          codeReference: "IS 456 Cl 38.1 Fig 21",
          description: "Depth from neutral axis where strain varies from 0 to 0.002 parabolically.",
          formulaRelation: "x_2 = \\frac{4}{7} x_u \\approx 0.57 x_u",
        },
        {
          id: "hs-05",
          xPercent: 78,
          yPercent: 32,
          label: "Total Compressive Force C = 0.36 fck b xu",
          codeReference: "IS 456 Cl 38.1",
          description: "Area of stress block multiplied by width b. Acts at 0.42 xu from top edge.",
          formulaRelation: "C = 0.36 f_{ck} b x_u",
        },
        {
          id: "hs-06",
          xPercent: 78,
          yPercent: 88,
          label: "Total Tension Force T = 0.87 fy Ast",
          codeReference: "IS 456 Cl 38.1(f)",
          description: "Tensile steel force, assuming steel yield strain has reached at least (0.87 fy / Es) + 0.002.",
          formulaRelation: "T = 0.87 f_y A_{st}",
        },
        {
          id: "hs-07",
          xPercent: 88,
          yPercent: 60,
          label: "Lever Arm z = d - 0.42 xu",
          codeReference: "IS 456 Cl 38.1",
          description: "Perpendicular distance between compressive resultant C and tensile resultant T.",
          formulaRelation: "z = d - 0.416 x_u",
        },
      ],
    },
    {
      id: "diag-02",
      title: "Three-Phase Soil System (Air, Water, Solids)",
      category: "soil_mechanics",
      categoryName: "Geotechnical & Soil Mechanics",
      subjectName: "Geotechnical Engineering",
      caption: "Volumetric and Gravimetric representation of soil constituents (Solid particles, Water voids, and Air voids).",
      accessibilityText: "Diagram depicts a 3-phase soil block divided vertically into Solids (bottom), Water (middle), and Air (top). On the left is the volume axis: Total Volume V, Volume of Solids Vs, Volume of Voids Vv, Volume of Water Vw, and Volume of Air Va. On the right is the weight axis: Total Weight W, Weight of Solids Ws, Weight of Water Ww, and Weight of Air Wa = 0.",
      isCodeReference: "IS 2720 Part 1 Soil Classification",
      svgType: "soil_phase",
      linkedFormulaId: "f-geo-01",
      linkedMcqTopic: "Basic Properties & Phase Relations",
      keyTakeaways: [
        "Total Volume V = Vs + Vw + Va = Vs + Vv.",
        "Total Weight W = Ws + Ww (Weight of air Wa is assumed negligible = 0).",
        "Void Ratio e = Vv / Vs (can be greater than 1.0 or 100%).",
        "Porosity n = Vv / V (always strictly between 0 and 100%).",
        "Degree of Saturation Sr = Vw / Vv (Sr = 0 for dry, Sr = 1 for saturated).",
        "Fundamental Relation: Sr * e = w * Gs.",
      ],
      hotspots: [
        {
          id: "hs-sp-01",
          xPercent: 15,
          yPercent: 20,
          label: "Volume of Air (Va)",
          description: "Portion of void space occupied by air. Zero in fully saturated soil.",
          formulaRelation: "V_a = V_v - V_w",
        },
        {
          id: "hs-sp-02",
          xPercent: 15,
          yPercent: 48,
          label: "Volume of Water (Vw)",
          description: "Volume occupied by pore water.",
          formulaRelation: "V_w = \\frac{W_w}{\\gamma_w}",
        },
        {
          id: "hs-sp-03",
          xPercent: 15,
          yPercent: 80,
          label: "Volume of Solids (Vs)",
          description: "Incompressible mineral volume of soil grains.",
          formulaRelation: "V_s = \\frac{W_s}{G_s \\gamma_w}",
        },
        {
          id: "hs-sp-04",
          xPercent: 85,
          yPercent: 20,
          label: "Weight of Air = 0",
          description: "Weight of air is neglected in engineering calculations.",
          formulaRelation: "W_a \\approx 0",
        },
        {
          id: "hs-sp-05",
          xPercent: 85,
          yPercent: 48,
          label: "Weight of Water (Ww)",
          description: "Mass/weight of pore fluid.",
          formulaRelation: "W_w = w \\cdot W_s",
        },
        {
          id: "hs-sp-06",
          xPercent: 85,
          yPercent: 80,
          label: "Weight of Solids (Ws / Md)",
          description: "Oven dry mass of soil particles.",
          formulaRelation: "W_s = \\frac{W}{1 + w}",
        },
      ],
    },
    {
      id: "diag-03",
      title: "Mohr's Circle of Plane Stress & Principal Planes",
      category: "structural_mechanics",
      categoryName: "Strength of Materials",
      subjectName: "Strength of Materials",
      caption: "Graphical representation of 2D transformation of normal stress (sigma) and shear stress (tau).",
      accessibilityText: "Diagram shows Mohr's circle plotted on Cartesian axes with normal stress sigma on X-axis and shear stress tau on Y-axis. The center is at ((sigma_x + sigma_y)/2, 0) and radius R is the maximum shear stress. Principal stresses sigma_1 and sigma_2 are the X-intercepts where tau = 0.",
      isCodeReference: "Timoshenko Mechanics of Solids",
      svgType: "mohr_circle",
      linkedFormulaId: "f-som-02",
      linkedMcqTopic: "Principal Stresses and Strains",
      keyTakeaways: [
        "Center of Mohr's circle = ((sigma_x + sigma_y) / 2, 0).",
        "Radius R = sqrt(((sigma_x - sigma_y) / 2)^2 + tau_xy^2) = Maximum in-plane shear stress.",
        "Major Principal Stress sigma_1 = Center + R.",
        "Minor Principal Stress sigma_2 = Center - R.",
        "On principal planes, shear stress is ALWAYS zero.",
        "Angle between principal plane and max shear plane is 45 degrees in real space (90 degrees on Mohr circle).",
      ],
      hotspots: [
        {
          id: "hs-mc-01",
          xPercent: 50,
          yPercent: 50,
          label: "Center of Circle C = ((sigma_x + sigma_y)/2, 0)",
          description: "Average normal stress on the element.",
          formulaRelation: "\\sigma_{avg} = \\frac{\\sigma_x + \\sigma_y}{2}",
        },
        {
          id: "hs-mc-02",
          xPercent: 85,
          yPercent: 50,
          label: "Major Principal Stress (sigma_1)",
          description: "Maximum normal stress; shear stress is zero at this point.",
          formulaRelation: "\\sigma_1 = \\frac{\\sigma_x + \\sigma_y}{2} + \\sqrt{\\left(\\frac{\\sigma_x - \\sigma_y}{2}\\right)^2 + \\tau_{xy}^2}",
        },
        {
          id: "hs-mc-03",
          xPercent: 15,
          yPercent: 50,
          label: "Minor Principal Stress (sigma_2)",
          description: "Minimum normal stress on the element.",
          formulaRelation: "\\sigma_2 = \\frac{\\sigma_x + \\sigma_y}{2} - \\sqrt{\\left(\\frac{\\sigma_x - \\sigma_y}{2}\\right)^2 + \\tau_{xy}^2}",
        },
        {
          id: "hs-mc-04",
          xPercent: 50,
          yPercent: 15,
          label: "Max Shear Stress (tau_max = Radius R)",
          description: "Peak shear stress acting on planes oriented at 45° to principal planes.",
          formulaRelation: "\\tau_{max} = \\frac{\\sigma_1 - \\sigma_2}{2} = R",
        },
      ],
    },
    {
      id: "diag-04",
      title: "Highway Cross-Section Elements & IRC 73 Standards",
      category: "transportation_cross_sections",
      categoryName: "Highway & Transportation",
      subjectName: "Highway Engineering",
      caption: "Two-lane rural highway cross section showing carriageway, camber, shoulders, roadway width, and Right-of-Way (RoW) as per IRC 73.",
      accessibilityText: "Cross-section showing a crown in center with 2.5% camber sloping to paved and earthen shoulders (3.0% - 4.0% camber), side drains, building lines, control lines, and total Right of Way.",
      isCodeReference: "IRC 73:1980 Rural Highway Cross-Sections",
      svgType: "highway_cross_section",
      linkedFormulaId: "f-trans-01",
      linkedMcqTopic: "Geometric Design of Highways",
      keyTakeaways: [
        "Carriageway width for two-lane with kerbs = 7.5 m (without kerbs = 7.0 m).",
        "Shoulder width = 2.5 m (Paved + Earthen).",
        "Pavement Camber: 2.0% - 2.5% for Bituminous / Thin Premix, 1.7% - 2.0% for Concrete.",
        "Shoulder camber is kept 0.5% steeper than carriageway camber (Min 3.0%).",
      ],
      hotspots: [
        {
          id: "hs-hw-01",
          xPercent: 50,
          yPercent: 35,
          label: "Crown & Camber (1 in n)",
          codeReference: "IRC 73 Table 4.1",
          description: "Transverse slope provided to drain surface rainwater quickly off the carriageway.",
          formulaRelation: "y = \\frac{2x^2}{n W}",
        },
        {
          id: "hs-hw-02",
          xPercent: 30,
          yPercent: 40,
          label: "Carriageway Width (7.0 m for 2-Lane)",
          codeReference: "IRC 73 Cl 4.3",
          description: "Width of paved surface intended for vehicular movement.",
          formulaRelation: "W = 7.0\\text{ m}",
        },
        {
          id: "hs-hw-03",
          xPercent: 18,
          yPercent: 45,
          label: "Shoulder (2.5 m width)",
          codeReference: "IRC 73 Cl 4.4",
          description: "Emergency lane for broken-down vehicles and lateral structural support.",
          formulaRelation: "W_{sh} = 2.5\\text{ m}",
        },
        {
          id: "hs-hw-04",
          xPercent: 5,
          yPercent: 65,
          label: "Side Drain & Right-of-Way (RoW)",
          codeReference: "IRC 73 Table 4.5",
          description: "Total land acquisition boundary for National Highway (Open rural: 45m).",
        },
      ],
    },
  ];

  static getDiagrams(category?: DiagramCategory): VisualDiagram[] {
    if (!category || category === ("all" as any)) {
      return this.diagrams;
    }
    return this.diagrams.filter((d) => d.category === category);
  }

  static getDiagram(id: string): VisualDiagram | null {
    return this.diagrams.find((d) => d.id === id) || null;
  }
}
